str="hello,and welcome \nto my world!"

print(str.capitalize())
print(str.casefold())
print(str.center(40))
print(str.count("and"))
print(str.endswith("!"))
print(str.expandtabs(20))
print(str.find("world"))
print(str.index("welcome"))
print(str.expandtabs(20))
print(str.isalnum())
print(str.isalpha())
print(str.isdecimal())
print(str.islower())
print(str.isprintable())
print(str.isspace())
print(str.isupper())
print(str.lower())
print(str.rfind("wel"))
print(str.rindex("wel"))
print(str.rsplit())
print(str.split())
print(str.splitlines())
print(str.startswith("t"))
print(str.swapcase())
print(str.title())
print(str.upper())
print(str.zfill(30))

